# This file is machine-generated - editing it directly is not advised

julia_version = "1.10.0"
manifest_format = "2.0"
project_hash = "e43e493ac0bbd48a97b7b420bf090975b7968865"

[[deps.GameBoy]]
deps = ["OffsetArrays"]
git-tree-sha1 = "c1a01d7a2dcc8f18c66838cff28552f6a8ab5e14"
uuid = "6fb4242f-1e24-4c34-aea5-7820002b36ca"
version = "0.9.2"

[[deps.OffsetArrays]]
git-tree-sha1 = "6a731f2b5c03157418a20c12195eb4b74c8f8621"
uuid = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"
version = "1.13.0"

    [deps.OffsetArrays.extensions]
    OffsetArraysAdaptExt = "Adapt"

    [deps.OffsetArrays.weakdeps]
    Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
