@enum Item begin
    NoItem
    MasterBall
    UltraBall
    GreatBall
    PokeBall
    TownMap
    Bicycle
    Surfboard
    SafariBall
    Pokedex
    MoonStone
    Antidote
    BurnHeal
    IceHeal
    Awakening
    ParlyzHeal
    FullRestore
    MaxPotion
    HyperPotion
    SuperPotion
    Potion
    Boulderbadge
    Cascadebadge
    SafariBait
    SafariRock
    Thunderbadge
    Rainbowbadge
    Soulbadge
    Marshbadge
    Volcanobadge
    Earthbadge
    EscapeRope
    Repel
    OldAmber
    FireStone
    ThunderStone
    WaterStone
    HpUp
    Protein
    Iron
    Carbos
    Calcium
    RareCandy
    DomeFossil
    HelixFossil
    SecretKey
    UnusedItem
    BikeVoucher
    XAccuracy
    LeafStone
    CardKey
    Nugget
    PpUp2
    PokeDoll
    FullHeal
    Revive
    MaxRevive
    GuardSpec
    SuperRepel
    MaxRepel
    DireHit
    Coin
    FreshWater
    SodaPop
    Lemonade
    SSTicket
    GoldTeeth
    XAttack
    XDefend
    XSpeed
    XSpecial
    CoinCase
    OaksParcel
    Itemfinder
    SilphScope
    PokeFlute
    LiftKey
    ExpAll
    OldRod
    GoodRod
    SuperRod
    PpUp
    Ether
    MaxEther
    Elixer
    MaxElixer
    FloorB2f
    FloorB1f
    Floor1f
    Floor2f
    Floor3f
    Floor4f
    Floor5f
    Floor6f
    Floor7f
    Floor8f
    Floor9f
    Floor10f
    Floor11f
    FloorB4f
    HM01_Cut
    HM02_Fly
    HM03_Surf
    HM04_Strength
    HM05_Flash
    TM01_MegaPunch
    TM02_RazorWind
    TM03_SwordsDance
    TM04_Whirlwind
    TM05_MegaKick
    TM06_Toxic
    TM07_HornDrill
    TM08_BodySlam
    TM09_TakeDown
    TM10_DoubleEdge
    TM11_Bubblebeam
    TM12_WaterGun
    TM13_IceBeam
    TM14_Blizzard
    TM15_HyperBeam
    TM16_PayDay
    TM17_Submission
    TM18_Counter
    TM19_SeismicToss
    TM20_Rage
    TM21_MegaDrain
    TM22_Solarbeam
    TM23_DragonRage
    TM24_Thunderbolt
    TM25_Thunder
    TM26_Earthquake
    TM27_Fissure
    TM28_Dig
    TM29_Psychic
    TM30_Teleport
    TM31_Mimic
    TM32_DoubleTeam
    TM33_Reflect
    TM34_Bide
    TM35_Metronome
    TM36_Selfdestruct
    TM37_EggBomb
    TM38_FireBlast
    TM39_Swift
    TM40_SkullBash
    TM41_Softboiled
    TM42_DreamEater
    TM43_SkyAttack
    TM44_Rest
    TM45_ThunderWave
    TM46_Psywave
    TM47_Explosion
    TM48_RockSlide
    TM49_TriAttack
    TM50_Substitute
end
