name: Documenter
on:
  push:
    branches:
      - main
    tags: '*'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: documenter
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1.10'
      - name: Set up custom registry
        run: julia -e 'using Pkg; pkg"registry add General https://github.com/meltedtofu/MeltedTofuRegistry.git"'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For authentication with GitHub Actions token
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }} # For authentication with SSH deploy key
        run: julia --project=docs/ docs/make.jl
